"""
Generate rich artifacts for MLflow: HTML lineage graph, Markdown summary,
and run overview note that renders on the MLflow run page.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any, Dict, List, Optional


def generate_lineage_html(
    *,
    feature_service_name: str,
    feature_refs: List[str],
    data_sources: List[str],
    entity_keys: List[str],
    run_id: str,
    project: str,
    feature_views: Optional[List[Any]] = None,
) -> str:
    """Generate a self-contained HTML file with an interactive Mermaid lineage graph."""

    fv_names = set()
    if feature_views:
        for fv in feature_views:
            fv_names.add(fv.name if hasattr(fv, "name") else str(fv))
    else:
        for ref in feature_refs:
            if ":" in ref:
                fv_names.add(ref.split(":")[0])
            elif "__" in ref:
                fv_names.add(ref.split("__")[0])

    mermaid_lines = ["graph LR"]

    for ds in data_sources:
        ds_id = ds.replace("/", "_").replace(".", "_").replace("-", "_")
        mermaid_lines.append(f'  ds_{ds_id}["{ds}"]')

    for fv in fv_names:
        fv_id = fv.replace("-", "_")
        mermaid_lines.append(f'  fv_{fv_id}["{fv}"]')
        for ds in data_sources:
            ds_id = ds.replace("/", "_").replace(".", "_").replace("-", "_")
            mermaid_lines.append(f"  ds_{ds_id} --> fv_{fv_id}")

    fs_id = feature_service_name.replace("-", "_")
    mermaid_lines.append(f'  fs_{fs_id}["{feature_service_name}"]:::fsNode')
    for fv in fv_names:
        fv_id = fv.replace("-", "_")
        mermaid_lines.append(f"  fv_{fv_id} --> fs_{fs_id}")

    short_id = run_id[:8]
    mermaid_lines.append(f'  run_{short_id}["MLflow Run {short_id}"]:::runNode')
    mermaid_lines.append(f"  fs_{fs_id} --> run_{short_id}")

    mermaid_lines.append("  classDef fsNode fill:#238636,stroke:#2ea043,color:#fff")
    mermaid_lines.append("  classDef runNode fill:#1565c0,stroke:#1976d2,color:#fff")

    mermaid_graph = "\n".join(mermaid_lines)

    features_html = "".join(f"<li><code>{r}</code></li>" for r in feature_refs)

    return f"""<!DOCTYPE html>
<html><head>
<meta charset="UTF-8">
<title>Feast Lineage - {feature_service_name}</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #0d1117; color: #e6edf3; padding: 24px; }}
  h1 {{ font-size: 20px; color: #58a6ff; }}
  h2 {{ font-size: 16px; margin-top: 24px; color: #8b949e; }}
  .mermaid {{ margin: 24px 0; }}
  code {{ background: #21262d; padding: 2px 6px; border-radius: 4px; font-size: 13px; }}
  ul {{ margin: 8px 0; padding-left: 24px; }}
  li {{ margin: 4px 0; }}
  .meta {{ color: #8b949e; font-size: 13px; }}
</style>
</head><body>
<h1>Feast Feature Lineage</h1>
<p class="meta">Project: {project} | Feature Service: {feature_service_name} | Run: {run_id[:12]}...</p>
<div class="mermaid">
{mermaid_graph}
</div>
<h2>Features ({len(feature_refs)})</h2>
<ul>{features_html}</ul>
<h2>Data Sources</h2>
<ul>{"".join(f"<li>{ds}</li>" for ds in data_sources)}</ul>
<h2>Entities</h2>
<ul>{"".join(f"<li>{e}</li>" for e in entity_keys)}</ul>
<script>mermaid.initialize({{ theme: 'dark', startOnLoad: true }});</script>
</body></html>"""


def generate_lineage_markdown(
    *,
    feature_service_name: str,
    feature_refs: List[str],
    data_sources: List[str],
    entity_keys: List[str],
    run_id: str,
    project: str,
) -> str:
    """Generate a Markdown summary for MLflow's artifact viewer."""

    features_list = "\n".join(f"- `{r}`" for r in feature_refs)
    sources_list = "\n".join(f"- {ds}" for ds in data_sources)
    entities_list = "\n".join(f"- {e}" for e in entity_keys)

    return f"""# Feast Feature Lineage

| Field | Value |
|-------|-------|
| **Project** | {project} |
| **Feature Service** | {feature_service_name} |
| **MLflow Run** | `{run_id}` |
| **Features** | {len(feature_refs)} |
| **Entities** | {len(entity_keys)} |
| **Data Sources** | {len(data_sources)} |

## Features

{features_list}

## Data Sources

{sources_list}

## Entity Keys

{entities_list}

---
*Auto-generated by feast-mlflow native integration*
"""


def generate_run_note(
    *,
    feature_service_name: str,
    project: str,
    num_features: int,
    num_entities: int,
    feast_ui_url: str = "",
) -> str:
    """Generate HTML content for mlflow.note.content tag (renders on run overview)."""

    link = ""
    if feast_ui_url:
        link = f' | <a href="{feast_ui_url}" target="_blank">View in Feast UI</a>'

    return (
        f'<div style="padding:12px;background:#161b22;border:1px solid #30363d;border-radius:8px;font-family:sans-serif">'
        f'<b style="color:#58a6ff">Feast Features</b>{link}<br>'
        f'<span style="color:#8b949e">Service:</span> {feature_service_name} | '
        f'<span style="color:#8b949e">Project:</span> {project} | '
        f'{num_features} features, {num_entities} entities'
        f"</div>"
    )


def log_feast_artifacts(
    *,
    mlflow_module: Any,
    feature_service_name: str,
    feature_refs: List[str],
    data_sources: List[str],
    entity_keys: List[str],
    run_id: str,
    project: str,
    feature_views: Optional[List[Any]] = None,
    feast_ui_url: str = "",
) -> None:
    """Log all rich Feast artifacts to the active MLflow run."""

    with tempfile.TemporaryDirectory() as tmpdir:
        html_content = generate_lineage_html(
            feature_service_name=feature_service_name,
            feature_refs=feature_refs,
            data_sources=data_sources,
            entity_keys=entity_keys,
            run_id=run_id,
            project=project,
            feature_views=feature_views,
        )
        html_path = Path(tmpdir) / "feast_lineage.html"
        html_path.write_text(html_content)
        mlflow_module.log_artifact(str(html_path))

        md_content = generate_lineage_markdown(
            feature_service_name=feature_service_name,
            feature_refs=feature_refs,
            data_sources=data_sources,
            entity_keys=entity_keys,
            run_id=run_id,
            project=project,
        )
        md_path = Path(tmpdir) / "feast_lineage.md"
        md_path.write_text(md_content)
        mlflow_module.log_artifact(str(md_path))

    note = generate_run_note(
        feature_service_name=feature_service_name,
        project=project,
        num_features=len(feature_refs),
        num_entities=len(entity_keys),
        feast_ui_url=feast_ui_url,
    )
    mlflow_module.set_tag("mlflow.note.content", note)
